### ISSUE TITLE
Discuss and reconsider color-by-distance scale

### ISSUE THREAD

**Issue by opatut** [openbikesensor/portal#118]
It is arbitrary right now and should probably be discussed and improved.

**Comment by gluap** [comment]
Currently the color-distance style matches well with the 1.5 metre rule that is valid within city boundaries (zone=DE:urban) in Germany. Unfortunately this makes the map green on rural roads where cars are faster and a 2.0 metre rule applies - even if the mean overtaking distance is way below the limit.

On the long term the scale should become "ruralness"-aware, on the short term we might say goodbye to the "green-red" transition and instead use less suggestive colors.

**Comment by opatut** [comment]
I agree with the fact that right now they are wrong. I think we can normalize the values based on the legal minimum, have a scale where 0 is 0cm and 1 is the minimum legal passing distance, then have a color ramp going from 0.5 or so to 1.5 or so. We'll only have to show the color maps in meters, distinct by rural/urban, because I think a normalized scale is not that easy to understand when reading the map.

We could also just have one scale and two rows of values next to it, labeled accordingly:

![image](https://user-images.githubusercontent.com/235784/146756294-c99b5a5d-55d8-4151-ba6a-6d2e5d8e62b0.png)

(I'd flip it probably, urban on top, rural on bottom, but this would be the general idea).

**Comment by gluap** [comment]
So the Idea would be to use the normalized distance for the coloring and keep the raw distance values in the tile data for the information table?

I'd also be a fan of making the "rural" property visible long-term in the "segment" detail view.

I agree on piling this with other schema changes.

One quick-and-dirty way that wasn't mentioned yet would be to allow the user to switch between "2 metre rule colors" and "1.5 metre rule colors".

**Comment by opatut** [comment]
> So the Idea would be to use the normalized distance for the coloring and keep the raw distance values in the tile data for the information table?

Yes, but not for the information table. That one works differently, and doesn't depend on tile data, it does the lookup directly in the database with a special request. But in general, yes, I'd like to keep the actual distance in the tile data, as it is the baseline information and people might want to use it directly for different visualizations etc.

> One quick-and-dirty way that wasn't mentioned yet would be to allow the user to switch between "2 metre rule colors" and "1.5 metre rule colors".

That sounds like a good idea to get a quick improvement by just adding a tiny UI toggle, and then later we can make it generic with a tile change. Would you want to implement this for now, @gluap?

**Comment by gluap** [comment]
I think this is obsolete now. - We have a new color scale and we also have the distinction of rural <> urban
