### ISSUE TITLE
Single Track View not usable on mobile

### ISSUE THREAD

**Issue by boldt** [openbikesensor/portal#123]
Die Info-Box verdeckt auf dem Handy die komplette Karte:

![Screenshot_20211201-094539](https://user-images.githubusercontent.com/750793/144201562-b2adb8fd-55bb-4507-924b-b7d7c239ebea.png)

Idee: Die Info-Box einklappbar machen.

**Comment by opatut** [comment]
Thanks for the report. I think we should just put the info contents below the map on mobile.

**Comment by opatut** [comment]
Hot fixed will be in 0.3.4 -- for a proper fixing of all pages, #129 was created.
