### ISSUE TITLE
Show My Tracks when clicking on Tracks

### ISSUE THREAD

**Issue by Ventusfahrer** [openbikesensor/portal#136]
![Bildschirmfoto von 2021-12-05 18-20-16](https://user-images.githubusercontent.com/5901190/144757669-25161a28-d232-44c5-a9e9-daae1410070c.png)

At the moment I am more interested in ***My Tracks*** than in a list of latest uploaded tracks which are visible to public. 
May be this will change in future, but then I would like to use additional filters on public tracks.

**Comment by opatut** [comment]
How about we put "My tracks" on the right, near your avatar, then keep "Tracks" on the left the public list, and remove the tabs on top of the list (where your arrow is pointing)?

Adding customizable filters will be a different issue I guess.

**Comment by klausgoe** [comment]
I Propse to add the entry "My Tracks" to the list OpenBikeSensor Map Tracks. Then you have 
OpenBikeSensor Map (public)Tracks My Tracks
and you can directly switch/click to your own tracks. That avoids context dependant switching of content.

**Comment by Ventusfahrer** [comment]
my original thought was:

when I login to the portal I am primary focused on my tracks, therefore reduce the amount of actions to get to them.

This is my initial idea, when opening the issue:
![Variant-0](https://user-images.githubusercontent.com/5901190/144765358-78de0159-cd95-4559-b736-110cc0bc98bd.png)
after clicking on ***Tracks*** I get a list of My Tracks and on the second Tab the ***Tracks***. I have to click on Tracks to get the list of the Public Tracks them. Maybe one can also rename Tracks on this level to "Public Tracks".

The second variant is probably the one you supposed (?):
![Variant-1](https://user-images.githubusercontent.com/5901190/144765460-aabf1347-9a24-498b-906a-f7430a1b04f9.png)
This would allow to remove the 2nd Tab-Level, fine idea, which I like.

The third variant:
![Variant-2](https://user-images.githubusercontent.com/5901190/144765562-6a58339c-c486-438f-b0c1-90b261c7f1f1.png)

puts ***My Tracks*** to the User-Menu. This looks logical, but takes two clicks and moving the mouse to get to my tracks.

**Comment by opatut** [comment]
Yeah, I thought about the menu too, but as you said, that is a primary action and takes two clicks, so it's not really an improvement.

I don't like the first option due to the "Tracks" button changing meaning based on your login state. So let's go with the second one ("My tracks" in top menu on the right).

**Comment by opatut** [comment]
![image](https://user-images.githubusercontent.com/235784/144810332-6aec4bb2-a242-4eaa-93c3-64bce217784e.png)

**Comment by klausgoe** [comment]
Don't know wether it matters, but I agree ;-)
