### ISSUE TITLE
Segment direction is reversed

### ISSUE THREAD

**Issue by gluap** [openbikesensor/portal#142]
The direction in the road analysis seems to be reversed.

The screenshots below show a rather steep downhill westward direction. But the analysis looks like the cyclists in westwards direction were much slower. On this segment of road one will easily go up to 10m/s without pedaling, so it seems that the directions are reversed.

eastwards (uphill) display, note: driver is displayed around 33km/h
![image](https://user-images.githubusercontent.com/44007906/146657127-898da137-da35-4331-ad1d-0a25860cd419.png)

westwards, (downhill) display note: driver is around 10 km/h
![image](https://user-images.githubusercontent.com/44007906/146657154-f30e79bc-a65b-4595-b287-a03364f7c0b0.png)

I checked on one or two other segments with downhill and these were consistent with the assumption.

**Comment by opatut** [comment]
What a good catch. I was already wondering about a place near me.

**Comment by opatut** [comment]
Here is an even better image of the issue:

![image](https://user-images.githubusercontent.com/235784/146677506-636b5d7e-87f5-4d7d-a803-50ef748412fc.png)

* Events all go in south-east direction (see text alignment).
* They are assigned to east-side road half.
* This is called the "north-west bound".
* This [road segment](https://www.openstreetmap.org/way/288082483) goes southwards in OSM.
* Therefore, north-west would be the "reverse" direction, which is as it should be the second tab.
* Let's inspect the database:

```
obs=# select distance_overtaker, direction_reversed from overtaking_event where way_id = 288082483;
 distance_overtaker | direction_reversed 
--------------------+--------------------
               1.83 | f
               1.93 | f
               1.61 | f
               0.44 | f
```

Yes, they are imported incorrectly.

**Comment by opatut** [comment]
I'm stupid, the events are imported correctly -- `direction_reversed = f` means they go forward, which is southwards. The visualization is wrong only :)

**Comment by opatut** [comment]
Fun, same mistake done twice. And it was the same that I did above -- False = not reversed = forwards. That's confusing ;)

**Comment by gluap** [comment]
Can confirm that after fetching ``main`` and re-running the sql initialization the visualization renders fine (without reimport, as expected)

![image](https://user-images.githubusercontent.com/44007906/146833879-3a8f3fc0-48ea-4187-adeb-62445a54d14a.png)
