### ISSUE TITLE
mapbox-gl.css net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by boldt** [openbikesensor/portal#145]
Im Portal sehe ich den folgenden Fehler:

> GET https://api.tiles.mapbox.com/mapbox-gl-js/v1.15.2/mapbox-gl.css net::ERR_ABORTED 404 (Not Found

![Bildschirmfoto von 2021-12-21 00-06-28](https://user-images.githubusercontent.com/750793/146844477-9f8f80ab-6e18-43be-8a91-8f123611c9e3.png)

**Comment by opatut** [comment]
Sounds like your ad blocker triggering. Also, #131 should remove that request.
