### ISSUE TITLE
Temporal filtering of events

### ISSUE THREAD

**Issue by gluap** [openbikesensor/portal#241]
[Feature wish from the forum](https://forum.openbikesensor.org/t/ich-wuensch-mir-ein-paar-neue-geaenderte-features/841) Currently the event data already contains the event time stamps. Based on the time stamp it would be possible to filter events on the map (even in-browser) according to when they were recorded. This would open up the possibility of easily gauging changes in the overtaking data i.e. after changes in traffic regulations or cycleway design.

The feature wish is about having the possibility to define a time window to filter event points (frontend-only) and possibly the accumulation to road segments (also backend) by event date and time.

**Comment by opatut** [comment]
Please see my [comment](https://github.com/openbikesensor/portal/issues/240#issuecomment-1114008056) regarding the implementation of such a filter. Possible, but tricky. Would be handy to have though, so I think it's worth trying.
