### ISSUE TITLE
Raw GPS track looks like a river

### ISSUE THREAD

**Issue by Nugman** [openbikesensor/portal#252]
It seems that the road snapping feature is snapping the track not only to streets but also to rivers:

See track https://portal.openbikesensor.org/tracks/5ej7q77a

![grafik](https://user-images.githubusercontent.com/15845695/173424629-3088a238-f67f-455b-ae71-9f24827b5294.png)

There is no path along the river.

Another example from the same track:
![grafik](https://user-images.githubusercontent.com/15845695/173426347-0a2ed26c-b8d2-4dca-a151-d0dbe16ddd13.png)

I followed the street straight on (yellow line). And as far as I know there is also no way to drive next to the river.

**Comment by opatut** [comment]
> And as far as I know there is also no way to drive next to the river.

There is no river there :) I [looked it up](https://www.openstreetmap.org/#map=18/50.06260/8.25765) to check the tags of that river, and did not find any. Then it dawned on me:

The blue line is your original GPS track without snapping, the pink line is the track snapped to a road.

So even though I built that feature myself, I still got confused. Apparently, the blue line is misleading, and we should change it. I am thinking the same pink color, but dotted or dashed, and less width. Definitely not blue though ;)

**Comment by Nugman** [comment]
LOL, that's a good one. Thanks for figuring out and apologies for the misleading bugreport.

Actually the location on the first screenshot has a river next to the road: https://www.openstreetmap.org/#map=17/50.12226/8.41784
So I assumed it might be the case in the second location also. Sometimes rivers are underground in urban areas ;-)
