### ISSUE TITLE
Add statistics overview to the entry page

### ISSUE THREAD

**Issue by amandel** [openbikesensor/portal#32]
There needs to be some motivation. Add something like:
* number of tracks uploaded
* tracked km
* confirmed pass events
* number of active users
* ..

For the last 
* month
* year
* ever

**Comment by opatut** [comment]
![test](https://user-images.githubusercontent.com/235784/118311865-c7131780-b4f0-11eb-8017-5c9d76ace2e2.gif)

**Comment by opatut** [comment]
Closed in b34fbb1ee74f7c6ddfb2a48f25133c3e5e236e0c.
