### ISSUE TITLE
Road usage not always unique

### ISSUE THREAD

**Issue by opatut** [openbikesensor/portal#335]
The road usage algorithm creates duplicates of (way_id, timestamp) tuples, so the hashes collide. The attached file has this problem: [pkx2e4aw.csv](https://github.com/openbikesensor/portal/files/11072758/pkx2e4aw.csv)

Let's fix that.

CC: @boldt

**Comment by gluap** [comment]
I checked my first Idea and it worked on second try - it is fixed in next.
