### ISSUE TITLE
ImportError: cannot import name 'CLOSED' from 'websockets

### ISSUE THREAD

**Issue by racsnet** [openbikesensor/portal#338]
After docker-compose up the worker and portal container throw this error:

` ImportError: cannot import name 'CLOSED' from 'websockets.connection' (/usr/local/lib/python3.9/site-packages/websockets/connection.py)`

It is a fresh installation of the Portal. Any ideas?

Edit: I have a workarround. See attached Pull request.

**Comment by gluap** [comment]
I just re-built the containers in the next branch and it seeps that the issue is fixed there already (even though "websocket" is not pinned, 10.4 is installed as probably other dependencies have pinned it by now).
