### ISSUE TITLE
Device alias is not saved

### ISSUE THREAD

**Issue by Nugman** [openbikesensor/portal#351]
In the profile menu one can set aliases ("Anzeigename") für different devices. Unfortunately the values are not saved and therefore not shown anywhere.

**Comment by gluap** [comment]
@Nugman there is indeed a problem with the "checkmark" icon when saving the device name. But it works by just pressing "enter" after inputting a new name. So you may use that as a workaround until the bug is fixed.

**Comment by Nugman** [comment]
Thx, that works!

**Comment by opatut** [comment]
I (re?)added buttons that should work. Will be in 0.9.0
