### ISSUE TITLE
Better statistics

### ISSUE THREAD

**Issue by Nugman** [openbikesensor/portal#356]
The statistics panel should have an additional line showing the absolute number of measurements below and above the minimum distance (1,50m/2m threshold) with a percentage. So you can see easily how much and how much percent of overtakings in that street happen with too less distance.

Also it would be nice to show the absolute numbers when hovering the mouse over the bars of the bar graphs.

![grafik](https://github.com/openbikesensor/portal/assets/15845695/f582dc0b-bbda-4cbe-b663-83f73e4930b1)

**Comment by opatut** [comment]
This is included in 0.9.0 to be released soon :)

![image](https://github.com/user-attachments/assets/5432d8e0-db3c-4ec5-80ed-94eb937def77)
