### ISSUE TITLE
Select multiple street segments

### ISSUE THREAD

**Issue by Nugman** [openbikesensor/portal#357]
Streets are segmented automatically from one junction to the next. In some cases on rural streets this leads to very short segments because of farm tracks. In real life I'd like to know the numbers for the whole length of the road - from one village to the next, in order to approach politicians to build a cycle path next to the road.
Therefore it would be nice if I could select multiple street segments with CTRL-Click and get a summarized statistics for all selected segments.

![grafik](https://github.com/openbikesensor/portal/assets/15845695/fde0c184-7b2f-4fd6-a54a-3977f51027a8)

**Comment by gluap** [comment]
Actually we do not segment, but load the segments as-is from osm. Depending on who mapped and how this does mean very long segments (also not always desirable) or very short ones. So multiselection makes sense.

**Comment by gluap** [comment]
There's already a request for this in #250

**Comment by opatut** [comment]
Closed as duplicate.
