### ISSUE TITLE
Deleted overtaking still on map

### ISSUE THREAD

**Issue by Discostu36** [openbikesensor/portal#358]
Maybe this is fixed in a later version, but on obs.adfc-luebeck.de (v. 0.7.0) deleted overtaking events are still shown in the map rendering.

![grafik](https://github.com/openbikesensor/portal/assets/30999326/14dcc89f-fb56-4085-a173-a371c1d8f50a)

Maybe related issue: #206

**Comment by gluap** [comment]
@boldt could we check the database together to see what happened to this event?
