### ISSUE TITLE
Road direction mixed up?

### ISSUE THREAD

**Issue by Nugman** [openbikesensor/portal#360]
It seems, like the direction of the road is mixed up between the map and the statistics table.

See: https://obs.adfc-hessen.de/map#21.70/50.13958253608688/8.37322566774414
When I select "Richtung Westen", the southern part of the road is highlighted, which leads actually to the east, because we drive on the right hand side. 
![image](https://github.com/openbikesensor/portal/assets/15845695/5334dc9d-27f8-46e1-9773-9f321c8758f3)

When I select "Richtung Osten", the northern side of the road is selected:
![image](https://github.com/openbikesensor/portal/assets/15845695/2ab836a0-c8ee-4a6b-b4ac-1dfa48d4c837)

Is this a bug or just a misunderstanding on my side?

**Comment by gluap** [comment]
@Nugman This looks indeed like a bug. I also checked the map but I don't think the segment shape is to blame. (was thinking that the segment was maybe s-shaped making it hard to decide between "west" and "east"-bound.

**Comment by gluap** [comment]
Yes, only "osten" / "westen" are the wrong way round. The statistics match the blue line on the map as far as i could tell.

**Comment by opatut** [comment]
This is fixed in `next` and will be in 0.9.0.
