### ISSUE TITLE
howto: use the production setup with nginx instead of traefik

### ISSUE THREAD

**Issue by ttjaden** [openbikesensor/portal#368]
Thanks for this great software project! 

Could you give me some short hints, how to change the production setup to use the portal with nginx instead of traefik? I have already a production server with several docker-applications but with nginx+certbot as reverse proxy

**Comment by gluap** [comment]
@ttjaden there's nothing special to observe for deployment behind nginx vs traefik. Just expose the two containers on the respective urls via nginx using the method you apply to your existing containers. We're not using special traefik features that would require involved traefik config.
