### ISSUE TITLE
OBS Fahrten 09. und 11.10. 

### ISSUE THREAD

**Issue by JoHo52** [openbikesensor/portal#372]
Hallo,
3 Fahrten im https://portal.openbikesensor.org/ unter Mathi05 werden nicht angezeigt. "Diese Fahrt wird gerade importiert, bitte lade die Seite später neu." Bei den beiden vom 09. ist die Route sichtbar, aber keine Punkte. Bei der von heute fehlt auch die Route.

**Comment by gluap** [comment]
Für das Upgrade auf die neuste portal Version werden gerade alle Fahrten neu berechnet, das dauert ein bisschen (evtl noch bis morgen).
