### ISSUE TITLE
Issue #372 besteht weiterhin: "Fahrten werden geladen"

### ISSUE THREAD

**Issue by JoHo52** [openbikesensor/portal#373]
Guten Abend,
die Fahrten unter Mathi05 im OpenBike Sensor Portal werden seit Freitag nicht ordentlich angezeigt. Von der am 11.10. hochgeladenen Fahrt existiert nur die Kennung; bei den früheren Fahrten wird die Route angezeigt, aber keine Messpunkte: "Diese Fahrt wird gerade importiert, bitte lade die Seite später neu." Am Samstag wurde das issue #372 geschlossen mit der Mitteilung, dass das Importieren noch etwas dauern würde, vielleicht bis zum nächsten Tag. Hoffentlich ist es bald wirklich so weit.
Beste Grüße
Joachim Hönes

**Comment by gluap** [comment]
Hallo Joachim,

das Importieren wurd irgendwann zwischen gestern, 11 uhr Morgens (da hatte ich zuletzt geschaut und es lief noch) und jetzt (da ist es fertig) abgeschlossen.
