### ISSUE TITLE
Richtungsanzeige für die Anzeige des Tracks

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/portal#41]
Wenn man nur einen Track pro Tag generiert, dann wäre es schön, wenn man nachträglich bei zwei Linien auf derselben Straße erkennen kann, welche Daten für welche Richtung sind.

**Comment by opatut** [comment]
![image](https://user-images.githubusercontent.com/235784/118358345-a396ae00-b57e-11eb-846e-e3c123bd427e.png)

Is this what you're looking for?
