### ISSUE TITLE
Kartenausschnitt vergrößern

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/portal#42]
Nicht zoomen, sondern die Karte selbst größer machen.

**Comment by Steffeng5** [comment]
@Natenom was genau meinst du? Hast du ggf einen Screenshot von deinem Track, da ich das nur anhand meiner kleinen Testdaten gebaut hatte das Zoomlevel. Glaube es sollte genau der ganze Track draufpassen

**Comment by Natenom** [comment]
Aktuell ist der Rahmen, in dem die Karte dargestellt wird, 400 x 1100 Pixel groß. Das ist zum "Stöbern" etwas wenig. Ich möchte das gerne auf Fullscreen umschalten können oder zumindest größer machen können.

**Comment by opatut** [comment]
Solved in next version, with a whole page just for the map.
