### ISSUE TITLE
Never Expose raw backend Messages to the Frontend

### ISSUE THREAD

**Issue by Steffeng5** [openbikesensor/portal#53]
copied from Slack:
{"errors":{"message":"Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.","error":{"ok":0,"code":96,"codeName":"OperationFailed","name":"MongoError"}}}

we should Never Never expose such messages to the Frontend.

**Comment by opatut** [comment]
Solved in Python rewrite via `DEBUG` config flag.
