### ISSUE TITLE
Better name for track when downloading

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/portal#54]
Currently when downloading a track it is always named track.gpx or track.csv.

Please use the name that was used for upload, for example "AutoUpload 2021-03-05T12.34.34-d1a8" as the base name.

**Comment by opatut** [comment]
Very good idea, I think this is part of #33

> Make sure when implementing this to use the filenames as advertised by the API

Well almost. I'll add it there as well, from a technical perspective these belong very much together ;)
