### ISSUE TITLE
Alignment(?) not correct

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/portal#72]
A track uploaded into the current online portal:
![track 2](https://user-images.githubusercontent.com/385995/118049613-43d1b480-b37e-11eb-9d0b-071b8cf7172a.png)

The same track in the current development portal:
![track 1](https://user-images.githubusercontent.com/385995/118049596-3e746a00-b37e-11eb-8da1-a579b8875b1b.png)

**Comment by opatut** [comment]
Oh, very good catch! Yeah I think I'm missing some data points in the pipeline, only exposing track information where a distance was recorded (even without button presses), but not the whole track. I'll see to this. 

Such an excellent idea, acutally comparing the two version!
