### ISSUE TITLE
Page numbers with many files

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/portal#76]
Starting from page 75:
![image](https://user-images.githubusercontent.com/385995/118206731-67225f80-b463-11eb-979c-4c410bdc420f.png)

After click on the right arrow(?):
![image](https://user-images.githubusercontent.com/385995/118206768-7e614d00-b463-11eb-9e74-8a6169b5f83e.png)

**Comment by opatut** [comment]
Wow, @Natenom, this truly is a bug only you could have discovered. How do you do it? :+1:
