### ISSUE TITLE
Portal responds with 200 to post to /api/tracks when openbikesensor mistakenly posts to frontend

### ISSUE THREAD

**Issue by gluap** [openbikesensor/portal#90]
I accidentally configured an openbikesensor with the frondend url instead of the backend url. 

**Observed behaviour:** Triggering an upload from the OBS will display an upload success on the display. No tracks are found on the portal afterwards though. 

Frontend logs 
```frontend_1  | 172.19.0.2 - - [02/Jul/2021:20:19:05 +0000] "POST /api/tracks HTTP/1.1" 200 2440```
 makes me suspect that OBS assumes successful upload based on Status code 200 (OK), therefore I'm filing in portal.

**expected behaviour**: success is only displayed when track actually was received by the api. 

I suspect in order to find out that it is posting to the wrong address, the OBS needs to get a non-200 response.

**Comment by boldt** [comment]
It's a known issues, but not reported yet 👍

**Comment by opatut** [comment]
It is solved since we've moved the api to `/api` and the frontend to `/`, so the new api will respond to `/api/tracks`, but the route should be `/api/api/tracks` instead, so it generates a 404 now. See: https://portal.openbikesensor.org/api/tracks
